### PR TITLE
Added HMAC-SHA256 as a signature method to OAUTH1

### PR DESCRIPTION
**Pull request by amccarter**
I needed support for HMAC-SHA256 for a project

### CODE REVIEW

**Comment by hallem** [comment]
looks good so far... you just need to add some unit tests then I can finish the review and get it merged in

**Comment by amccarter** [comment]
All of my unit tests pass now.

I'm not sure when this failure is with the RestSharp.IntegrationTests.AsyncTests.Can_Cancel_GET_TaskAsync test... I never touched that one.

**Comment by hallem** [comment]
There's something wrong with that test running in the CI environment.  I've not figured it out yet.

**Comment by amccarter** [comment]
Do you need anything further from me on this one?

**Pull request merged**
