### PR TITLE
cleanup: Fix parameter naming case inconsistency in `RestRequestExtension.cs`

### PR DESCRIPTION
**Pull request by ztl8702**
## Purpose
This pull request is a:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

_Might_ be breaking because we are changing a named argument. Existing call sites that uses [Named argument](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#named-arguments) might fail to compile.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/restsharp/RestSharp?pullRequest=1986) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/restsharp/RestSharp?pullRequest=1986) before we can accept your contribution.<br/><br/>:x: ztl8702 [sign now](https://cla.dotnetfoundation.org/restsharp/RestSharp?pullRequest=1986)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/restsharp/RestSharp?pullRequest=1986) it.</sub>

**Comment by ztl8702** [comment]
Unable to sign CLA:
Screen Shot 2022-12-18 at 3 30 44 pm

**Comment by ztl8702** [comment]
thanks

**Comment by ztl8702** [comment]
Lol I have a bad habit of not writing commit messages well.
image

Was assuming the maintainer would squash + modify commit message.

**Pull request merged**
