### PR TITLE
Added Restsharp.UWP project

### PR DESCRIPTION
**Pull request by DSchmidlin**
Adjust RestSharp code with #defines as some .Net namespaces/classes/methods aren't available when targeting UWP.

### CODE REVIEW

**Comment by DSchmidlin** [comment]
I did not try all build types but 'AnyCPU' was functional for my in my project

**Comment by calloncampbell** [comment]
Hopefully this gets merged. I'm very interested in using RestSharp in my UWP project.

**Comment by hallem** [comment]
it's been merged but the PR didn't add the project to the build scripts.  if you want to do this go for it if not then it will have to wait until i have time to figure out the nuget package targeting.

**Comment by JoshuaKGoldberg** [comment]
Can this be added to master please?

**Comment by hallem** [comment]
@JoshuaKGoldberg currently it cannot be added to nuget.  this PR didn't include the updated to the nuget build process and I have not been able to figure out the correct nuget targeting for it quite yet.  Until I do or @DSchmidlin adds to this it will only be apart of the source.

**Pull request merged**
