### PR TITLE
Xml node with attributes and content at the same time

### PR DESCRIPTION
**Pull request by bcichonski**
#963 proposed implementation

### CODE REVIEW

**Comment by alexeyzimarev** [comment]
Please rebase and squash.

**Comment by bcichonski** [comment]
I see commits have been squashed already - thanks. I have looked (briefly) at those conflicts and it seems to me that they could be resolved mostly by accepting my changes or all the methods (in tests), unfortunately I don't have write access to do so. Please let me know if I could help in any way.

**Comment by bcichonski** [comment]
I see commits have been squashed already - thanks. I have looked (briefly) at those conflicts and it seems to me that they could be resolved mostly by accepting my changes or all the methods (in tests), unfortunately I do not have write access to do so. Please let me know if i could help in any way.

**Comment by alexeyzimarev** [comment]
You can rebase, you only need access to your own branch to do so. You can just follow these instructions: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

Please remember to review the diffs for any merge because some stuff that was changed is important. If you encounter using `var` where you use explicit type - this is OK, you can keep your code as-is.

**Comment by bcichonski** [comment]
I did squashing and rebasing, but now 19 deserialization tests fail. As far as I remember, it was not so in June. Worse still, I have some strange problems when debugging these tests. I can not access the source library of RestSharp from the test library, what also worked well before. I need more time to investigate.

**Pull request merged**
