### PR TITLE
Set minimum System.Text.Json version to 5.0.1

### PR DESCRIPTION
**Pull request by LauraArmitage**
## Description

Fix https://github.com/restsharp/RestSharp/issues/1899

### CODE REVIEW

**Comment by alexeyzimarev** [comment]
Thanks for the fix. One question: why have you removed the open upper version constraint?

**Comment by LauraArmitage** [comment]
Sorry, I've not done this right - I was just trying to merge this into my fork. I've not tested this yet
From [this doc](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges) I interpret that `[5.0,)` sets an inclusive minimum only and this would be the same but with a higher minimum version.

**Comment by alexeyzimarev** [comment]
I think it could be `[5.0.1,)`

**Comment by alexeyzimarev** [comment]
Could also be `(5.0,)`. Yes, I think your current implementation is correct, I didn't read the docs correctly.

**Comment by LauraArmitage** [comment]
Thanks, I'll mark this as ready for review once I've tested

**Pull request merged**
