### PR TITLE
Fix file upload with non-ancii characters in a filename

### PR DESCRIPTION
**Pull request by soft-cactus**
## Description
This is a fix for file upload with non-ASCII characters in a filename eg. ÄÖäö.jpg.
Before it was converting the ContentDisposition.FileName to smth like "=?utf-8?B?BDFSDFasdfasdc==?="
Initially, it's an issue with ContentDispositionHeaderValue (microsoft/referencesource#140), but I don't know how to fix it there

## Purpose
This pull request is a:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by alexeyzimarev** [comment]
Thank you for the PR. Could you please also add an issue and describe what happens now, and what you expect to happen?

**Comment by soft-cactus** [comment]
an issue created - #1828 
I'll fix the failing tests if the fix makes sense

**Comment by alexeyzimarev** [comment]
Still waiting for tests :)

**Comment by soft-cactus** [comment]
tests are done :)

**Pull request closed without merging**
