### PR TITLE
 Added Option to add Interceptors

### PR DESCRIPTION
**Pull request by fseidl-bauradar**
## Description

Added Possibility to add Client wide Interceptors, to check Request and Responses on multiple positions

## Purpose
This pull request is a:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by fseidl-bauradar** [comment]
> The test project is in the wrong place and doesn't have the project file. I don't think it has any tests either.

I didn't changed the possition, as far as I see there are sub Projects inside the test folder.
Which contain the tests.

**Comment by alexeyzimarev** [comment]
Also, those interfaces can't be used alone as you can't add, for example, a class that implements `IBeforeSerializationInterceptor` to the interceptors list because the class must implement the `IInterceptor` interface. Based on that, I think it would be easier to have a base abstract class (that's how gRPC interceptors work) with empty virtual methods that can be overridden. With the current implementation you'd need to implement all the methods even if you want to intercept only one thing.

**Comment by alexeyzimarev** [comment]
> > The test project is in the wrong place and doesn't have the project file. I don't think it has any tests either.
> 
> I didn't changed the possition, as far as I see there are sub Projects inside the test folder. Which contain the tests.

Here's how the `Tests` solution folder looks like:

image

And the `ConsoleTest` directory is on the top level, it has no tests and no project file:

image

**Comment by fseidl-bauradar** [comment]
> > > The test project is in the wrong place and doesn't have the project file. I don't think it has any tests either.
> > 
> > 
> > I didn't changed the possition, as far as I see there are sub Projects inside the test folder. Which contain the tests.
> 
> Here's how the `Tests` solution folder looks like:
> 
> image
> 
> And the `ConsoleTest` directory is on the top level, it has no tests and no project file:
> 
> image

Oh seems like there is a little to much in the Pull Request, I originally wanted to exclude the ConsoleTest Project, from Repository.
It was just a little playgroud for setting up and test if the Interceptor is working as expected

**Comment by fseidl-bauradar** [comment]
> I don't think you needed to change this file:
> 
> image

You are right, but Rider mentioned it, and I aggree with it. As far I know Classes should always start with UpperCase

**Pull request closed without merging**
