### PR TITLE
Hotfix (refactor) RestClient.BuildUri(IRestRequest) method

### PR DESCRIPTION
**Pull request by lsolano**
Little improvement to this method. 

All tests run as before the change.

### CODE REVIEW

**Comment by hallem** [comment]
thanks for the pr.  two questions:
1. what's the impetus for the change
2. what is the need for the dependency on the nunit test adapter?  can the tests be created without it?

**Comment by hallem** [comment]
oh and don't worry about the failing unit test.  i'm not sure what's going on with appveyor on that one and i'm still trying to figure it out

**Comment by lsolano** [comment]
Hello Michael,


Answering your questions:

   1. There is no impetus to do this change, I'm was just looking through
   the code and tried to cleanup the code a little bit to better state what
   the method does (without the details), improving the maintainability:
      1. All required validations (Line 295)
      2. From the request extract both the base uri and the resource with
      all param values applied (Line 297)
      3. Merge the base url and the resource (Line 302)
      4. Finally to the merged URI apply all query string parameters (if
      any) (Line 304)
   2. About the NUnit test adapter: I'm using NUnit 3, they made some
   breaking change between v2.x and v3.x of their framework now you require 2
   different adapters one for each mayor version. So in order to run the
   project tests without changing the NUnit framework version (2.x => 3.x) I
   was forced to install the NUnit 2.x Test Adapter as a dependency for the
   test projects so Visual Studio can discoverer and run tests from the GUI. I
   think (didn't test it), that with both NUnit 2.x and 3.x installed on my
   box and using the Console Runner, the tests can run without that dependency.

About the failing test: Before I start changing the code, just after adding
the Test Adapter dependency, I ran all tests just to be sure not to break
something after the refactor. I noticed that 1 tests always fails and 4 or
5 were skipped. So I don't think the problem is with Appveyor.


Regards,
Lorenzo Solano Martínez

e-mail:       lorenzo.sm@gmail.com

G+:            https://plus.google.com/+LorenzoSolano
Cell phone: +1-829-276-7676

LinkedIn:    http://do.linkedin.com/pub/lorenzo-solano/33/551/a84
Skype ID:   lsolano.rd

**Comment by lsolano** [comment]
See the offending test (on my box), something with Date Parse of a JSON
data.

**Comment by alexeyzimarev** [comment]
@lsolano is it still relevant?

**Comment by lsolano** [comment]
@alexeyzimarev  In order to improve maintainability my vote is "Yes"

**Comment by alexeyzimarev** [comment]
I would be happy to merge if you remove all changes in the csproj file and rebase the `RestClient` to the latest develop.

**Comment by lsolano** [comment]
@alexeyzimarev Please check the changes now.

**Pull request merged**
