### PR TITLE
mark ErrorException as nullable to match interface

### PR DESCRIPTION
**Pull request by mhornbacher**
## Description

This resolves issue #1547 and related issues

## Purpose
This pull request is a:

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works (no additional tests needed)
- [x] I have added necessary documentation (matches existing documentation)

### CODE REVIEW

**Comment by mhornbacher** [comment]
Hu, it seems that the test suite failed to build the project, `dotnet test` runs fine locally...

**Comment by alexeyzimarev** [comment]
@mhornbacher thanks 👍 

Some tests are inconclusive due to the build agent specifics, I guess.

**Comment by mhornbacher** [comment]
Hu, not so happy merging to `dev`/`main` a commit where the test suite does not run. I wonder if it has to do with using C# 8 nullable on non-interface code.

**Comment by mhornbacher** [comment]
Hu, it would seem that other PR's are having the exact same issue: https://github.com/restsharp/RestSharp/pull/1546/checks?check_run_id=1588074709

**Pull request merged**
