### PR TITLE
WIP: First draft Extended Compression Support

### PR DESCRIPTION
**Pull request by driekus77**
## Description
First draft and WORK IN PROGRESS! of my issue: https://github.com/restsharp/RestSharp/issues/1438

This issue turned out to be a future request for extended Compression support especially the gzip compression.

## Purpose
This pull request is a:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

NOTE: Serializers interfaces are extended with new methods.

## Checklist

- [1 unittest class] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Again this is Work in Progress. I'm not convinced my provided solution is the way to go but at this time, and due to lack of time, I can not think of anything better. Review comments are appreciated!

I've created and tested it with only 1 UnitTest class containing 2 methods. All these and existing serializer tests succeed. But more testing is needed.

### CODE REVIEW

**Comment by driekus77** [comment]
Just tried to add Deflate/Inflate and Brotli support to this PR. Deflate/Inflate succeeded the last did not.  Lets see this PR and code as a starting point for a good discussion, if you will. 

# Chaining serializers
As far as I can see currently it is not yet possible to chain 2 or more serializers together in one pack/block.  This because e.g. UseSerializer code uses a SerializerFactory thats:
- Allowing usage of one serializer at a time
- Focused on DataFormat and (indirect) Mime-Type but not Content-Encoding and not Carrier/Transfer type (string or byte[])

## Chain Compressor and Serializer together: UseCompression(...)
I tried to overcome above issues by creating a different Serializer(Sink) for Compression that has its own IComposer interface. But still the chaining is tight (To tight if you ask me) because UseCompression takes only two arguments: Chained Serializer(JSon/Xml/...) and ICompressor(Gzip/Deflat/Brotli/...).

## Chain Serializer and Compressor together: UseSerializer(..., ICompressor comp = null)
The other way around, if you prefer this one better, is extending the UseSerializer with a IComposer parameter.

## Introduce Pipeline?
Above two Chaining subjects are still tight and support only one block of Serializer/Compressor.
Why not, if we are already thinking of breaking changes, Introduce some sort of Pipeline to make all serializers interchangeable as long as Mime-Types match.

I must overthink this Pipeline idea more but leave it for now...

## Other topics

- Content negotiating can become a topic: Compressors don't always compress (See threshold beneath). 
- Threshold: Approx. 1kb to 4kb is most of the time taken as threshold because beneath this compression has no usage because compression will likely be larger than uncompressed.

Feel free to add any thoughts about above...

Kind regards,

**Comment by driekus77** [comment]
Some more detail thoughts about PipeLine idea in beneath UML.
Note: I know lots of functionality is already covered inside RestSharp. But I don't see how to add Serializer(Transformer) chaining functionality without really breaking stuff.

PipeProposal

**Comment by alexeyzimarev** [comment]
Awesome, I will go through this tonight!

**Comment by driekus77** [comment]
Last update: Committed my design diagrams (Class diagram and Object diagram)

Maybe I'm a bit over designing but lets make sure that we don't forget a thing or two...

Class diagram:
https://github.com/restsharp/RestSharp/blob/df8272552074ef41e83e79f5c84f30d2c00879dc/docs/design/Class%20Diagram%20RestSharp%20Pipe(Line)%20Proposal.jpg?raw=true


Object diagram:
https://github.com/restsharp/RestSharp/blob/df8272552074ef41e83e79f5c84f30d2c00879dc/docs/design/Object%20Diagram%20RestSharp%20Pipe(Line)%20Proposal.jpg?raw=true

Again feedback is welcome.

**Comment by driekus77** [comment]
Maybe I was jumping into Conclusion(s)/Solution(s) to soon with suggesting a Pipeline idea. I was curious if I was/am the only one missing the Serializers being chainable and have explicit influance on it.

Also wanted to have a future support of e.g. flow based streaming e.g. connecting 2 or more flows conditionally.  https://en.wikipedia.org/wiki/Flow-based_programming

In order to not break existing Serializer functionallity my idea was to introduce Pipe(line). This pipe could, only when provided, runtime replace the serializer(s) usage. The implementation could, for the main part be done through Extensions and special package.

This PR code has, in my opinion not much use any more. Should I close it?

Note: Much going on in the world right now. But for me programming is a welcome diversion. 

Kind regards,

**Pull request closed without merging**
