### PR TITLE
dotnet rc2 support (version 2)

### PR DESCRIPTION
**Pull request by StefH**
1]
Use ifdef REMOTECERTVALIDATION for RemoteCertificateValidationCallback

2] Some frameworks are missing in project.json
- WindowsPhone.8.0
- WindowsPhone.8.1

### CODE REVIEW

**Comment by mariustom** [comment]
Any progress?

**Comment by nate-fr** [comment]
Any news ?

**Comment by ferrod20** [comment]
Any news?

**Comment by akuseru** [comment]
Would love to see this!

**Comment by behoyh** [comment]
Why does UriHelper use so much preprocessor directives?

**Comment by alexeyzimarev** [comment]
I would like to close this PR since `project.json` is irrelevant now. Concerning Windows Phone 8.X support, I would love to deprecate it. Anyone who uses it can keep using the older version. UWP will be supported.

**Pull request closed without merging**
