### PR TITLE
V109

### PR DESCRIPTION
**Pull request by EdLichtman**
## Description

Cherry-Picked Commit of pull request 2002. 
Includes: Better Documentation, and some tests for reliability and self-documentation

## Purpose
This pull request is a:

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ X ] I have added tests that prove my fix is effective or that my feature works
- [ X ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by tacosontitan — APPROVED** [review]

**Comment by tacosontitan** [comment]
This PR also considers the prior feedback from PR #2002 to utilize the code tag in the documentation.

<sub>*This was supposed to be included with my review above.*</sub>

**Comment by alexeyzimarev** [comment]
It's me who does the merge :)

**Comment by EdLichtman** [comment]
I tested the Koala test locally and it seems to be a transient error on the build server. Could it be due to request caps?

**Comment by alexeyzimarev** [comment]
I will check, it was not failing before. Weird.

**Pull request merged**
