### PR TITLE
Add support for .NET Core 1.0

### LINKED ISSUE #664: Are there any plans on supporting aspnet 5 and aspnet core 5 support ?
Are there any plans on supporting aspnet 5 and aspnet core 5 support ?

### PR DESCRIPTION
**Pull request by dgiagio**
This change adds support for .NET Core 1.0 with Visual Studio 2015 Update 3. Minimal code changes needed, mostly conditional compilation. Should fix #664.
# Requirements
- Visual Studio 2015 Update 3
- .NET Core 1.0 for Visual Studio

### CODE REVIEW

**Comment by BHSPitMonkey** [comment]
Seems like the AppVeyor config will need to be updated, no?

**Comment by ah-** [comment]
Ping.

**Comment by T-Boss** [comment]
Any possibility of getting this merged? I'd like to use .NET Core in a project, but can't until this is merged.

**Comment by Pokerkoffer** [comment]
when will this merged? Can a maintainer comment on this? Thanks :)

**Comment by kylelaverty** [comment]
Based on the front page, the giant help wanted logo, it appears there is no longer sufficient support to continue work on this solution.

**Comment by douglasg14b** [comment]
Any update on potential merge issues holding this back? Really need .NetCore compatibility.

**Comment by Andrei-Rinea** [comment]
Any update on this?

**Comment by alexeyzimarev** [comment]
We will be migrating to .NET Core 1.1 and new VS2017 format. We will not have a separate package for .NET Core.

**Pull request closed without merging**
