### PR TITLE
add connection groupname

### PR DESCRIPTION
**Pull request by cembasaranoglu**
## Purpose
This pull request is a:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by cembasaranoglu** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-assign-user-information-to-group-connections

**Comment by alexeyzimarev** [comment]
In order for the PR to be accepted, please:

- Fix the formatting
- Remove empty lines
- Provide proper description
- Remove the binary file

**Comment by cembasaranoglu** [comment]
Add comment(s) and the fix format

**Comment by alexeyzimarev** [comment]
Check the diff. The formatting is still wrong.

**Comment by alexeyzimarev** [comment]
Please consider fixing the PR or closing it.

**Comment by alexeyzimarev** [comment]
I have to do it myself.

**Pull request closed without merging**
