### PR TITLE
Separately set the "name" and "Content-Type" of a Multi-Part Form Data

### PR DESCRIPTION
**Pull request by EricYan1**
Used to set the Content-Type in a multipart form data to the name the user passed.
For example,

```
restRequest.AddParameter("comment", "{\"text\":\"This is a comment.\"}", ParameterType.RequestBody); 
```
would generate this multi-part form data:

-------------------------------28947758029299
Content-Type: comment
Content-Disposition: form-data; name="comment"

{"text":"This is a comment"}
-------------------------------28947758029299

Instead,

```
restRequest.AddParameter("comment", "{\"text\":\"This is a comment.\"}", "application/json",  ParameterType.RequestBody); 
``` 
can now generate this multi-part form data:

-------------------------------28947758029299
Content-Type: application/json
Content-Disposition: form-data; name="comment"

{"text":"This is a comment"}
-------------------------------28947758029299

### CODE REVIEW

**Comment by hallem** [comment]
Thanks for the PR.  It looks like you missed the async implementation on HTTP and didn't create any unit tests to verify your code works.  Once that stuff is added I'll merge it in and get a new version cut.

**Comment by EricYan1** [comment]
Thanks for the reply. I've added 2 tests that test for POST requests that don't contain entity bodies and 2 tests that test for multipart requests that contain a body with a file.

**Comment by EricYan1** [comment]
Hi is there anything else you'd like requested?

Thanks.

**Comment by hallem** [comment]
no there isn't, but the build is failing and i need to check why

**Comment by hallem** [comment]
merged in manually

**Pull request closed without merging**
