### PR TITLE
Add RemoteCertificateValidationCallback for .NET 4.5 and Above via RestClient

### LINKED ISSUE #620: Per request ServerCertificateValidationCallback
Currently I use

ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => { return true; }; 

to ignore SSL certificate check, but this is globally configuration, can we have per request setting like

HttpWebRequest request = HttpWebRequest.CreateHttp(url);
request.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => { return true; };

### PR DESCRIPTION
**Pull request by cogree**
Fixes #620 by adding a ```RemoteCertificateValidationCallback``` on ``IRestClient`` and passing it all the way to the creation of the ```HttpWebRequest``` for custom per-request certificate validation.

### CODE REVIEW

**Comment by cogree** [comment]
Not exactly sure why the appveyor build is failing. The failing test is marked with:
```
#if !APPVEYOR
        [Test]
        public void Can_Cancel_GET_TaskAsync()
        {
            ...
        }
#endif
```

**Comment by EduardKhudaiberdin** [comment]
It will be nice to have those changes in source code.

**Comment by hallem** [comment]
Don't worry about the failing test... It's something that has been plaguing me for a while and I haven't been able to figure out why it's not being ignored or failing.

**Comment by pmezykowski** [comment]
Sorry for digging this topic out, but I'm looking for this feature as well, but my instance of `RestClient` class doesn't have `RemoteCertificateValidationCallback` property (I'm using ver 105.2.3 for .NET 4.5.1).
Can it be that this is just because `NET45` flag is defined only for `debug` configuration in .csproj, but not for `release`?

**Comment by cogree** [comment]
v105.2.3 was released on 8/26/2015 and is quite dated (https://github.com/restsharp/RestSharp/releases). A new version needs uploaded to NuGet to use this feature. You can can still compile the source in ``master`` manually if you need it right away.

**Comment by pmezykowski** [comment]
That's true, I just checked that this is the newest on NuGet, didn't check the date :/
Is there a plan for release updated version to NuGet in near future?

**Comment by getlin** [comment]
Hello,

The latest nuget version is 105.2.3. Do you have any plan to release a new one soon?
I am especially interested in certificate validation feature #811 . 

Thanks

**Pull request merged**
